default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  password: "##ali##!@#$%"

development:
  <<: *default
  database: fustany_task_development

test:
  <<: *default
  database: fustany_task_test

production:
  <<: *default
  database: fustany_task_production
  username: fustany_task
  password: <%= ENV['FUSTANY_TASK_DATABASE_PASSWORD'] %>
